// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/board" | "/cookies" | "/cookies/policy" | "/forgot-password" | "/login" | "/onboarding" | "/privacy" | "/reset-password" | "/share/[token]" | "/signup" | "/sso-callback/[[...sso-callback]]" | "/termos" | "/terms"
type AppRouteHandlerRoutes = "/api/auth/session" | "/api/conversations" | "/api/conversations/[id]" | "/api/conversations/[id]/messages" | "/api/conversations/[id]/share" | "/api/conversations/[id]/title" | "/api/onboarding" | "/api/onboarding/bootstrap" | "/api/plans" | "/api/plans/[id]" | "/api/plans/[id]/review" | "/api/share/[token]" | "/api/strategies" | "/api/strategies/[id]" | "/api/terms/accept"
type PageRoutes = never
type LayoutRoutes = "/" | "/board" | "/onboarding"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/session": {}
  "/api/conversations": {}
  "/api/conversations/[id]": { "id": string; }
  "/api/conversations/[id]/messages": { "id": string; }
  "/api/conversations/[id]/share": { "id": string; }
  "/api/conversations/[id]/title": { "id": string; }
  "/api/onboarding": {}
  "/api/onboarding/bootstrap": {}
  "/api/plans": {}
  "/api/plans/[id]": { "id": string; }
  "/api/plans/[id]/review": { "id": string; }
  "/api/share/[token]": { "token": string; }
  "/api/strategies": {}
  "/api/strategies/[id]": { "id": string; }
  "/api/terms/accept": {}
  "/board": {}
  "/cookies": {}
  "/cookies/policy": {}
  "/forgot-password": {}
  "/login": {}
  "/onboarding": {}
  "/privacy": {}
  "/reset-password": {}
  "/share/[token]": { "token": string; }
  "/signup": {}
  "/sso-callback/[[...sso-callback]]": { "sso-callback"?: string[]; }
  "/termos": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/board": never
  "/onboarding": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
